
export const API2_URL = 'https://api2.splinterlands.com';
export const GAME_API_URL = 'https://game-api.splinterlands.io'
export const IMG_ROOT_URL = 'https://d36mxiodymuqjm.cloudfront.net/website';
export const LEAGUES = {
  0: 'Novice',
  1: 'Bronze 3',
  2: 'Bronze 2',
  3: 'Bronze 1',
  4: 'Silver 3',
  5: 'Silver 2',
  6: 'Silver 1',
  7: 'Gold 3',
  8: 'Gold 2',
  9: 'Gold 1',
  10: 'Diamond 3',
  11: 'Diamond 2',
  12: 'Diamond 1',
  13: 'Champion 3',
  14: 'Champion 2',
  15: 'Champion 1',
};
export const BRAWL_STATUS = [
  'Preparation Stage',
  'Battle Stage',
  'Result Stage',
];

export const BRAWL_TIER = {
  1: { tier: 1},
  2: { tier: 1},
  3: { tier: 2},
  4: { tier: 2},
  5: { tier: 3},
  6: { tier: 3},
  7: { tier: 4},
  8: { tier: 4},
  9: { tier: 5},
  10: { tier: 5},
}

export const FRAYS = {
  1: [
    '1 All Novice',
    '2	All Novice',
    '3	Chaos + RW Novice',
    '4	U+D+C+RW Novice',
    '5	All Bronze',
    '6	All Bronze',
    '7	Chaos + RW Bronze',
    '8	All Silver',
    '9	All Silver',
    '10	Chaos + RW Silver',
    '11	All	Gold Foil	Bronze',
    '12	Chaos + RW	Gold Foil	Bronze',
    '13	U+D+C+RW	Gold Foil	Bronze',
  ],
  2: [
    '1 All Novice',
    '2	Chaos + RW Novice',
    '3	All Bronze',
    '4	All Bronze',
    '5	Chaos + RW Bronze',
    '6	A+B+P+R Bronze',
    '7	All Silver',
    '8	All Silver',
    '9	Chaos + RW Silver',
    '10	U+D+C+RW Silver',
    '11	All',
    '12	U+D+C+RW',
    '13	All	Gold Foil	Bronze',
    '14	U+D+C+RW Gold Foil	Bronze',
    '15	All	Gold Foil	Silver',
    '16	U+D+C+RW Gold Foil	Silver',
  ],
  3: [
    '1	All Bronze',
    '2	U+D+C+RW Bronze',
    '3	All Silver',
    '4	All Silver',
    '5	U+D+C+RW Silver',
    '6	A+B+P+R Silver',
    '7	All',
    '8	All',
    '9	All',
    '10	U+D+C+RW',
    '11	Alpha Beta Promo Reward',
    '12	All Max',
    '13	U+D+C+RW Max',
    '14	All	Gold Foil	Bronze',
    '15	All	Gold Foil	Silver',
    '16	U+D+C+RW	Gold Foil	Silver',
    '17	All	Gold Foil	Gold',
    '18	U+D+C+RW	Gold Foil	Gold',
  ],
  4: [
    '1	All Silver',
    '2	All Silver',
    '3	U+D+C+RW Silver',
    '4	U+D+C+RW Silver',
    '5	All',
    '6	All',
    '7	All',
    '8	U+D+C+RW',
    '9	U+D+C+RW',
    '10	Alpha',
    '11	All Max',
    '12	All Max',
    '13	U+D+C+RW Max',
    '14	U+D+C+RW Max',
    '15	Alpha Beta Promo Reward Max',
    '16	All	Gold Foil	Bronze',
    '17	All	Gold Foil	Silver',
    '18	U+D+C+RW	Gold Foil	Silver',
    '19	All	Gold Foil	Gold',
    '20	U+D+C+RW	Gold Foil	Gold',
    '21	All	Gold Foil	Max',
  ],
  5: [
    '1	All Silver',
    '2	U+D+C+RW Silver',
    '3	All',
    '4	All',
    '5	All',
    '6	U+D+C+RW',
    '7	U+D+C+RW',
    '8	U+D+C+RW',
    '9	All Max',
    '10	All Max',
    '11	All Max',
    '12	All Max',
    '13	All Max',
    '14	U+D+C+RW Max',
    '15	U+D+C+RW Max',
    '16	U+D+C+RW Max',
    '17	Alpha Max',
    '18	Alpha Beta Promo Reward Max',
    '19	All	Gold Foil	Silver',
    '20	U+D+C+RW	Gold Foil	Silver',
    '21	All	Gold Foil	Gold',
    '22	U+D+C+RW	Gold Foil	Gold',
    '23	Alpha Beta Promo Reward	Gold Foil	Gold',
    '24	All	Gold Foil	Max',
    '25	U+D+C+RW	Gold Foil	Max',
  ]
}