
export const API2_URL = 'https://api2.splinterlands.com';
export const GAME_API_URL = 'https://game-api.splinterlands.io'
export const IMG_ROOT_URL = 'https://d36mxiodymuqjm.cloudfront.net/website';
export const LEAGUES = {
  0: 'Novice',
  1: 'Bronze 3',
  2: 'Bronze 2',
  3: 'Bronze 1',
  4: 'Silver 3',
  5: 'Silver 2',
  6: 'Silver 1',
  7: 'Gold 3',
  8: 'Gold 2',
  9: 'Gold 1',
  10: 'Diamond 3',
  11: 'Diamond 2',
  12: 'Diamond 1',
  13: 'Champion 3',
  14: 'Champion 2',
  15: 'Champion 1',
};
export const BRAWL_STATUS = [
  'Preparation Stage',
  'Battle Stage',
  'Result Stage',
];

export const BRAWL_TIER = {
  1: { tier: 1},
  2: { tier: 1},
  3: { tier: 2},
  4: { tier: 2},
  5: { tier: 3},
  6: { tier: 3},
  7: { tier: 4},
  8: { tier: 4},
  9: { tier: 5},
  10: { tier: 5},
}

export const FRAYS = [
  [
    '1 All	Regular	Novice',
    '2	All	Regular	Novice',
    '3	Chaos	Regular	Novice	Chaos + RW',
    '4	Alpha + Beta	Regular	Novice	U+D+C+RW',
    '5	All	Regular	Bronze',
    '6	All	Regular	Bronze',
    '7	Chaos	Regular	Bronze	Chaos + RW',
    '8	All	Regular	Silver',
    '9	All	Regular	Silver',
    '10	Chaos	Regular	Silver	Chaos + RW',
    '11	All	Gold Foil	Bronze',
    '12	Chaos	Gold Foil	Bronze	Chaos + RW',
    '13	All	Gold Foil	Silver	U+D+C+RW	Gold Foil	Bronze',
  ],
  [
    '1 All	Regular	Novice',
    '2	Chaos	Regular	Novice	Chaos + RW',
    '3	All	Regular	Bronze',
    '4	All	Regular	Bronze',
    '5	Chaos	Regular	Bronze	Chaos + RW',
    '6	Alpha + Beta	Regular	Bronze	A+B+P+R',
    '7	All	Regular	Silver',
    '8	All	Regular	Silver',
    '9	Chaos	Regular	Silver	Chaos + RW',
    '10	Untamed + Dice + Chaos	Regular	Silver	U+D+C+RW',
    '11	All	Regular	Gold',
    '12	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '13	All	Gold Foil	Bronze',
    '14	Untamed + Dice + Chaos	Gold Foil	Bronze	U+D+C+RW',
    '15	All	Gold Foil	Silver',
    '16	Untamed + Dice + Chaos	Gold Foil	Silver	U+D+C+RW',
  ],
  [
    '1	All	Regular	Bronze',
    '2	Untamed + Dice + Chaos	Regular	Bronze	U+D+C+RW',
    '3	All	Regular	Silver',
    '4	All	Regular	Silver',
    '5	Untamed + Dice + Chaos	Regular	Silver	U+D+C+RW',
    '6	Alpha	Regular	Silver	A+B+P+R',
    '7	All	Regular	Gold',
    '8	All	Regular	Gold',
    '9	All	Regular	Gold',
    '10	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '11	Alpha Beta Promo Reward	Regular	Gold',
    '12	All	Regular	Max',
    '13	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '14	All	Gold Foil	Bronze',
    '15	All	Gold Foil	Silver',
    '16	Untamed + Dice + Chaos	Gold Foil	Silver	U+D+C+RW',
    '17	All	Gold Foil	Gold',
    '18	Untamed + Dice + Chaos	Gold Foil	Gold	U+D+C+RW',
  ],
  [
    '1	All	Regular	Silver',
    '2	All	Regular	Silver',
    '3	Untamed + Dice + Chaos	Regular	Silver	U+D+C+RW',
    '4	Untamed + Dice + Chaos	Regular	Silver	U+D+C+RW',
    '5	All	Regular	Gold',
    '6	All	Regular	Gold',
    '7	All	Regular	Gold',
    '8	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '9	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '10	Alpha	Regular	Gold',
    '11	All	Regular	Max',
    '12	All	Regular	Max',
    '13	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '14	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '15	Alpha Beta Promo Reward	Regular	Max',
    '16	All	Gold Foil	Bronze',
    '17	All	Gold Foil	Silver',
    '18	Untamed + Dice + Chaos	Gold Foil	Silver	U+D+C+RW',
    '19	All	Gold Foil	Gold',
    '20	Untamed + Dice + Chaos	Gold Foil	Gold	U+D+C+RW',
    '21	All	Gold Foil	Max',
  ],
    '1	All	Regular	Silver',
    '2	Untamed + Dice + Chaos	Regular	Silver	U+D+C+RW',
    '3	All	Regular	Gold',
    '4	All	Regular	Gold',
    '5	All	Regular	Gold',
    '6	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '7	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '8	Untamed + Dice + Chaos	Regular	Gold	U+D+C+RW',
    '9	All	Regular	Max',
    '10	All	Regular	Max',
    '11	All	Regular	Max',
    '12	All	Regular	Max',
    '13	All	Regular	Max',
    '14	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '15	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '16	Untamed + Dice + Chaos	Regular	Max	U+D+C+RW',
    '17	Alpha	Regular	Max',
    '18	Alpha Beta Promo Reward	Regular	Max',
    '19	All	Gold Foil	Silver',
    '20	Untamed + Dice + Chaos	Gold Foil	Silver	U+D+C+RW',
    '21	All	Gold Foil	Gold',
    '22	Untamed + Dice + Chaos	Gold Foil	Gold	U+D+C+RW',
    '23	Alpha Beta Promo Reward	Gold Foil	Gold',
    '24	All	Gold Foil	Max',
    '25	Untamed + Dice + Chaos	Gold Foil	Max	U+D+C+RW',
]