
export const API2_URL = 'https://api2.splinterlands.com';
export const GAME_API_URL = 'https://game-api.splinterlands.io'
export const IMG_ROOT_URL = 'https://d36mxiodymuqjm.cloudfront.net/website';
export const LEAGUES = {
  0: 'Novice',
  1: 'Bronze 3',
  2: 'Bronze 2',
  3: 'Bronze 1',
  4: 'Silver 3',
  5: 'Silver 2',
  6: 'Silver 1',
  7: 'Gold 3',
  8: 'Gold 2',
  9: 'Gold 1',
  10: 'Diamond 3',
  11: 'Diamond 2',
  12: 'Diamond 1',
  13: 'Champion 3',
  14: 'Champion 2',
  15: 'Champion 1',
};
export const BRAWL_STATUS = [
  'Preparation Stage',
  'Battle Stage',
  'Result Stage',
];

export const BRAWL_TIER = {
  1: { tier: 1},
  2: { tier: 1},
  3: { tier: 2},
  4: { tier: 2},
  5: { tier: 3},
  6: { tier: 3},
  7: { tier: 4},
  8: { tier: 4},
  9: { tier: 5},
  10: { tier: 5},
}

export const FRAYS = [
  [
    '1 All	Regular	Novice',
    '2	All	Regular	Novice',
    '3	Chaos + RW	Regular	Novice',
    '4	U+D+C+RW	Regular	Novice',
    '5	All	Regular	Bronze',
    '6	All	Regular	Bronze',
    '7	Chaos + RW	Regular	Bronze',
    '8	All	Regular	Silver',
    '9	All	Regular	Silver',
    '10	Chaos + RW	Regular	Silver',
    '11	All	Gold Foil	Bronze',
    '12	Chaos + RW	Gold Foil	Bronze',
    '13	U+D+C+RW	Gold Foil	Bronze',
  ],
  [
    '1 All	Regular	Novice',
    '2	Chaos + RW	Regular	Novice',
    '3	All	Regular	Bronze',
    '4	All	Regular	Bronze',
    '5	Chaos + RW	Regular	Bronze',
    '6	A+B+P+R Regular	Bronze',
    '7	All	Regular	Silver',
    '8	All	Regular	Silver',
    '9	Chaos + RW	Regular	Silver',
    '10	U+D+C+RW Regular	Silver',
    '11	All	Regular	Gold',
    '12	U+D+C+RW Regular	Gold',
    '13	All	Gold Foil	Bronze',
    '14	U+D+C+RW Gold Foil	Bronze',
    '15	All	Gold Foil	Silver',
    '16	U+D+C+RW Gold Foil	Silver',
  ],
  [
    '1	All	Regular	Bronze',
    '2	U+D+C+RW Regular	Bronze',
    '3	All	Regular	Silver',
    '4	All	Regular	Silver',
    '5	U+D+C+RW Regular	Silver',
    '6	A+B+P+R	Regular	Silver',
    '7	All	Regular	Gold',
    '8	All	Regular	Gold',
    '9	All	Regular	Gold',
    '10	U+D+C+RW Regular	Gold',
    '11	Alpha Beta Promo Reward	Regular	Gold',
    '12	All	Regular	Max',
    '13	U+D+C+RW	Regular	Max',
    '14	All	Gold Foil	Bronze',
    '15	All	Gold Foil	Silver',
    '16	U+D+C+RW	Gold Foil	Silver',
    '17	All	Gold Foil	Gold',
    '18	U+D+C+RW	Gold Foil	Gold',
  ],
  [
    '1	All	Regular	Silver',
    '2	All	Regular	Silver',
    '3	U+D+C+RW	Regular	Silver',
    '4	U+D+C+RW	Regular	Silver',
    '5	All	Regular	Gold',
    '6	All	Regular	Gold',
    '7	All	Regular	Gold',
    '8	U+D+C+RW	Regular	Gold',
    '9	U+D+C+RW	Regular	Gold',
    '10	Alpha	Regular	Gold',
    '11	All	Regular	Max',
    '12	All	Regular	Max',
    '13	U+D+C+RW Regular	Max',
    '14	U+D+C+RW	Regular	Max',
    '15	Alpha Beta Promo Reward	Regular	Max',
    '16	All	Gold Foil	Bronze',
    '17	All	Gold Foil	Silver',
    '18	U+D+C+RW	Gold Foil	Silver',
    '19	All	Gold Foil	Gold',
    '20	U+D+C+RW	Gold Foil	Gold',
    '21	All	Gold Foil	Max',
  ],
    '1	All	Regular	Silver',
    '2	U+D+C+RW	Regular	Silver',
    '3	All	Regular	Gold',
    '4	All	Regular	Gold',
    '5	All	Regular	Gold',
    '6	U+D+C+RW	Regular	Gold',
    '7	U+D+C+RW	Regular	Gold',
    '8	U+D+C+RW	Regular	Gold',
    '9	All	Regular	Max',
    '10	All	Regular	Max',
    '11	All	Regular	Max',
    '12	All	Regular	Max',
    '13	All	Regular	Max',
    '14	U+D+C+RW	Regular	Max',
    '15	U+D+C+RW	Regular	Max',
    '16	U+D+C+RW	Regular	Max',
    '17	Alpha	Regular	Max',
    '18	Alpha Beta Promo Reward	Regular	Max',
    '19	All	Gold Foil	Silver',
    '20	U+D+C+RW	Gold Foil	Silver',
    '21	All	Gold Foil	Gold',
    '22	U+D+C+RW	Gold Foil	Gold',
    '23	Alpha Beta Promo Reward	Gold Foil	Gold',
    '24	All	Gold Foil	Max',
    '25	U+D+C+RW	Gold Foil	Max',
]